Make footer Component
belivvr/xrcloud-front-layout pull request #3
Opened 2022-09-05 05:46 UTC by sinde530

# 한일
-  mui install (material, icons-material)
- Footer 간단한 TDD 작성중
- Footer Navigation 생성
- 하던 도중에 스토리북 생성하고 잔에러가 좀 나서 시간이 걸렸습니다,,,

![image](https://user-images.githubusercontent.com/70146617/188369036-2539acad-0bee-498c-9d94-a56708bfb111.png)

<img width="641" alt="image" src="https://user-images.githubusercontent.com/70146617/188369077-49a1fa81-a1f2-4b15-81a0-1d70703a0379.png">

2022-09-05 05:55 UTC, juunini requested changes

2022-09-05 05:55 UTC, juunini commented on src/components/Footer/ListButton.test.tsx
> +    expect(iconElement).toBeInTheDocument()
이 테스트 코드를 보면

- '이용약관' 텍스트는 디폴트로 나오는거고
- 클릭 후에 아이콘이 나옴

으로 보여요.
icon에 꼭 https://play-lh.googleusercontent.com/yPtnkXQAn6yEahOurxuYZL576FDXWn3CqewVcEWJsXlega_nSiavBvmaXwfTGktGlQ=w240-h480-rw 를 써야 할 이유도 잘 모르곘어요.

클릭을 하지 않아도 커버리지는 가득 차지 않나요?
onClick 이벤트가 없으니까요

2022-09-05 05:57 UTC, juunini commented on src/components/Footer/ListButton.test.tsx
> +    expect(iconElement).toBeInTheDocument()
왠지 Footer만 랜더링 해도 커버리지가 가득 차지 않나 싶어요

2022-09-05 06:00 UTC, srain66 commented on src/components/Footer/ListButton.test.tsx
> +    expect(iconElement).toBeInTheDocument()
저도 이부분 테스트 보고 드랍다운 메뉴같은 건 줄 알았는데 component 보면 아닌 것 같아서 어느쪽으로 만드신 건지 잘 모르겠어요 가능하면 footer 모습을 찍어서 같이 올려주셨으면 좋겠어요

2022-09-05 06:08 UTC, juunini requested changes

2022-09-05 06:08 UTC, juunini commented on src/components/Footer/index.tsx
> +          <Navigation/>
이 컴포넌트의 이름은 왜 Navigation 인가요?

2022-09-05 06:08 UTC, juunini commented on src/components/Footer/ListButton.test.tsx
> +})
작동부분이 없는 컴포넌트라 테스트 안올려도
<Footer /> 만 랜더링 해도 커버리지가 차는거 아닌가요?

2022-09-05 06:32 UTC, juunini requested changes

2022-09-05 06:32 UTC, juunini commented on src/components/Footer/index.tsx
> +              <ListButton text="이용약관" link="/" />
음.... 이렇게 쓴다면 굳이 ListButton 이라는 컴포넌트를 만들어야 했나 싶어요

```tsx
const Item = styled(ListItemButton, {
  target="_blank"
  rel="noreferrer"
  disableRipple
  disableTouchRipple
  sx={{ '&:hover': { background: 'none' } }}
})({});

// ...

<Item href="https://www.facebook.com/groups/webxrko">
  <ForumIcon />
  WebXRCloud
</Item>
```

이런 느낌으로 써도 되지 않나 싶어요

2022-09-05 06:33 UTC, juunini requested changes

2022-09-05 06:33 UTC, juunini commented on src/components/Footer/index.tsx
> +            <List dense>
아래 위에는 dense가 없는데 왜 여기만 dense 가 있나요?

2022-09-06 02:01 UTC, juunini approved these changes
LGTM

2022-09-06 02:01 UTC, merged